#ifndef KERNEL_ISR_H
#define KERNEL_ISR_H

#include <kernel/types.h>

/* Field order must match the layout `pusha` leaves on the stack, lowest
 * address first. `pusha` pushes eax, ecx, edx, ebx, esp, ebp, esi, edi, and
 * the last push lands lowest — so reading upward gives edi first.
 *
 * The esp slot holds the value from before the pusha; `popa` ignores it.
 */
struct cpu_state {
  u32 edi;
  u32 esi;
  u32 ebp;
  u32 esp;
  u32 ebx;
  u32 edx;
  u32 ecx;
  u32 eax;
} __attribute__((packed));

/* What the CPU pushed, plus the error code. Vectors that do not push one of
 * their own get a zero supplied by the assembly stub, so this layout is the
 * same for every vector.
 */
struct stack_state {
  u32 error_code;
  u32 eip;
  u32 cs;
  u32 eflags;
} __attribute__((packed));

/* Called from common_interrupt_handler in src/arch/x86/isr.s */
void isr_dispatch(struct cpu_state *cpu, struct stack_state *stack,
                  u32 interrupt);

/* Per-vector entry stubs generated by the macros in src/arch/x86/isr.s.
 * Their addresses go into the IDT; they are never called from C. */
void interrupt_handler_14(void);
void interrupt_handler_33(void);

#endif /* KERNEL_ISR_H */
